# Generated by Django 5.2.12 on 2026-03-31 22:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome do Personagem')),
                ('background', models.CharField(choices=[('ION_OPERATIVE', 'ION Operative'), ('DISPLACED_PIRATE', 'Displaced Pirate'), ('AMNESIAC', 'Amnesiac'), ('OTHER', 'Outro')], default='OTHER', max_length=20, verbose_name='Background')),
                ('background_custom', models.CharField(blank=True, help_text='Preencha se escolheu "Outro".', max_length=120, verbose_name='Background (custom)')),
                ('base_rank', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)], verbose_name='Base Rank')),
                ('nl_rank', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='NL Rank')),
                ('agility', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Agility (AGI)')),
                ('fortitude', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Fortitude (FOR)')),
                ('insight', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Insight (INS)')),
                ('presence', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Presence (PRE)')),
                ('stability', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Stability (STA)')),
                ('intent', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Intent (INT)')),
                ('continuity_constant', models.CharField(blank=True, choices=[('', '—'), ('CC-S', 'CC-S — Spatial'), ('CC-T', 'CC-T — Temporal'), ('CC-M', 'CC-M — Material'), ('CC-B', 'CC-B — Biological'), ('CC-C', 'CC-C — Cognitive'), ('CC-N', 'CC-N — Causal')], default='', max_length=4, verbose_name='Continuity Constant')),
                ('abstraction_frame', models.CharField(blank=True, choices=[('', '—'), ('SHIFTER', 'Shifter'), ('CHANGER', 'Changer'), ('MAKER', 'Maker'), ('LEAKER', 'Leaker')], default='', max_length=10, verbose_name='Abstraction Frame')),
                ('current_hp', models.IntegerField(default=0, verbose_name='HP Atual')),
                ('temp_hp', models.IntegerField(default=0, verbose_name='HP Temporário')),
                ('armor_bonus', models.IntegerField(default=0, verbose_name='Bônus de Armadura')),
                ('shield_bonus', models.IntegerField(default=0, verbose_name='Bônus de Escudo')),
                ('current_load', models.IntegerField(default=0, verbose_name='Carga Atual')),
                ('skill_melee', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='Melee')),
                ('skill_ranged_weapons', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='Ranged Weapons')),
                ('skill_heavy_weaponry', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='Heavy Weaponry')),
                ('skill_initiative', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='Initiative')),
                ('skill_athletics', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='Athletics')),
                ('skill_endurance', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='Endurance')),
                ('skill_acrobatics', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='Acrobatics')),
                ('skill_stealth', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='Stealth')),
                ('skill_perception', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='Perception')),
                ('skill_reflexes', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='Reflexes')),
                ('skill_sleight_of_hand', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='Sleight of Hand')),
                ('skill_piloting_ground', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='Piloting (Ground)')),
                ('skill_piloting_air', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='Piloting (Air)')),
                ('skill_piloting_sea', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='Piloting (Sea)')),
                ('skill_technology', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='Technology')),
                ('skill_engineering', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='Engineering')),
                ('skill_medicine', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='Medicine')),
                ('skill_history', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='History')),
                ('skill_religion', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='Religion')),
                ('skill_investigation', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='Investigation')),
                ('skill_intuition', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='Intuition')),
                ('skill_persuasion', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='Persuasion')),
                ('skill_intimidation', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='Intimidation')),
                ('skill_deception', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='Deception')),
                ('skill_survival', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='Survival')),
                ('skill_null_theory', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='Null Theory')),
                ('skill_null_navigation', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='Null Navigation')),
                ('skill_animal_handling', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='Animal Handling')),
                ('skill_nlc', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='NL Control (NLC)')),
                ('skill_nlr', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='NL Resistance (NLR)')),
                ('skill_nl_sensitivity', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='NL Sensitivity')),
                ('skill_nl_engineering', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='NL Engineering')),
                ('skill_anomalous_protocols', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='Anomalous Protocols')),
                ('skill_continuity_analysis', models.CharField(choices=[('U', 'Untrained'), ('P', 'Proficient'), ('E', 'Expert'), ('M', 'Master')], default='U', max_length=1, verbose_name='Continuity Analysis')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personagem',
                'verbose_name_plural': 'Personagens',
                'ordering': ['-updated_at'],
            },
        ),
    ]
