# Generated by Django 5.2.12 on 2026-04-01 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharSheet', '0002_alter_character_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: GC1, D1, TA3, GO1, FA1, etc.', max_length=10, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=80, verbose_name='Nome')),
                ('category', models.CharField(choices=[('COMBAT', 'Combat'), ('OPERATIONS', 'Operations')], max_length=12, verbose_name='Categoria')),
                ('tree', models.CharField(help_text='Nome da tree (ex: Dodge Mastery, Tactician, General) ou "General".', max_length=40, verbose_name='Skill Tree')),
                ('tree_code', models.CharField(help_text='Prefixo da tree (ex: D, P, BL, GC, GO, FA, etc.).', max_length=10, verbose_name='Código da Tree')),
                ('tier', models.PositiveIntegerField(default=0, help_text='0 = general (sem tree), 1/2/3 = posição na árvore.', verbose_name='Tier na árvore')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('prerequisite', models.ForeignKey(blank=True, help_text='Feat necessária antes desta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks', to='CharSheet.featdefinition')),
            ],
            options={
                'verbose_name': 'Feat (Livro)',
                'verbose_name_plural': 'Feats (Livro)',
                'ordering': ['category', 'tree', 'tier', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CharacterFeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feats', to='CharSheet.character')),
                ('feat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='CharSheet.featdefinition')),
            ],
            options={
                'verbose_name': 'Feat do Personagem',
                'verbose_name_plural': 'Feats do Personagem',
                'unique_together': {('character', 'feat')},
            },
        ),
    ]
