# Generated by Django 5.2.12 on 2026-04-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharSheet', '0003_featdefinition_characterfeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='featdefinition',
            name='tree_description',
            field=models.TextField(blank=True, default='', help_text='Descrição do que a skill tree representa.', verbose_name='Descrição da Tree'),
        ),
        migrations.AlterField(
            model_name='featdefinition',
            name='tree',
            field=models.CharField(help_text='Nome da tree (ex: Dodge Mastery, Tactician, General).', max_length=40, verbose_name='Skill Tree'),
        ),
    ]
