# Generated by Django 5.2.12 on 2026-04-13 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharSheet', '0004_featdefinition_tree_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraitDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: LUCKY, FRAGILE, BG_PROTOCOL_BRED', max_length=40, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=80, verbose_name='Nome')),
                ('kind', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative'), ('BACKGROUND', 'Background')], max_length=12, verbose_name='Tipo')),
                ('cost', models.IntegerField(default=0, help_text='Positivo = custa TP (positive trait). Negativo = dá TP (negative trait). 0 = background.', verbose_name='Custo em TP')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('background_key', models.CharField(blank=True, help_text='Se BACKGROUND: qual background concede este trait.', max_length=30, verbose_name='Background (só para BG traits)')),
            ],
            options={
                'verbose_name': 'Trait (Livro)',
                'verbose_name_plural': 'Traits (Livro)',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CharacterTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='CharSheet.character')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='CharSheet.traitdefinition')),
            ],
            options={
                'verbose_name': 'Trait do Personagem',
                'verbose_name_plural': 'Traits do Personagem',
                'unique_together': {('character', 'trait')},
            },
        ),
    ]
