# Generated by Django 5.2.12 on 2026-04-19 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharSheet', '0006_character_current_ap'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('weight', models.PositiveIntegerField(default=1, verbose_name='Peso (slots)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('effect', models.TextField(verbose_name='Efeito')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumables', to='CharSheet.character')),
            ],
            options={
                'verbose_name': 'Consumível',
                'verbose_name_plural': 'Consumíveis',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VestmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('weight', models.PositiveIntegerField(default=1, verbose_name='Peso (slots)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('pd_bonus', models.IntegerField(default=0, verbose_name='Bônus de PD')),
                ('rd', models.IntegerField(default=0, verbose_name='RD')),
                ('block_bonus', models.IntegerField(default=0, verbose_name='Bônus de Block')),
                ('agi_penalty', models.IntegerField(default=0, verbose_name='Penalidade de AGI')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vestments', to='CharSheet.character')),
            ],
            options={
                'verbose_name': 'Vestimenta / Escudo',
                'verbose_name_plural': 'Vestimentas / Escudos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeaponItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('weight', models.PositiveIntegerField(default=1, verbose_name='Peso (slots)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('damage', models.CharField(help_text='Ex: 1d6 + 4', max_length=40, verbose_name='Dano')),
                ('hit_bonus', models.IntegerField(default=0, verbose_name='Bônus de Acerto')),
                ('crit_range', models.PositiveIntegerField(default=20, verbose_name='Margem de Crítico')),
                ('crit_multiplier', models.PositiveIntegerField(default=2, verbose_name='Multiplicador de Crítico')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='CharSheet.character')),
            ],
            options={
                'verbose_name': 'Arma',
                'verbose_name_plural': 'Armas',
                'ordering': ['name'],
            },
        ),
    ]
