# Generated by Django 5.2.12 on 2026-04-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharSheet', '0007_consumableitem_vestmentitem_weaponitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaponitem',
            name='ammo',
            field=models.PositiveIntegerField(blank=True, help_text='Deixe vazio para armas corpo-a-corpo', null=True, verbose_name='Munição'),
        ),
        migrations.AddField(
            model_name='weaponitem',
            name='range_hexes',
            field=models.PositiveIntegerField(default=1, verbose_name='Alcance (hexes)'),
        ),
    ]
