# Generated by Django 5.2.12 on 2026-04-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharSheet', '0008_weaponitem_ammo_weaponitem_range_hexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='current_strain',
            field=models.IntegerField(default=0, verbose_name='Strain Atual'),
        ),
        migrations.AddField(
            model_name='featdefinition',
            name='nl_frame',
            field=models.CharField(blank=True, choices=[('', 'General (todos os frames)'), ('SHIFTER', 'Shifter'), ('CHANGER', 'Changer / Anchor'), ('MAKER', 'Maker'), ('LEAKER', 'Leaker')], default='', help_text='Vazio = geral (todos os frames). Preencher apenas para feats NON_LINEAR frame-específicas.', max_length=10, verbose_name='Frame NL'),
        ),
        migrations.AlterField(
            model_name='featdefinition',
            name='category',
            field=models.CharField(choices=[('COMBAT', 'Combat'), ('OPERATIONS', 'Operations'), ('NON_LINEAR', 'Non-Linear')], max_length=12, verbose_name='Categoria'),
        ),
    ]
