# Generated by Django 5.2.12 on 2026-04-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharSheet', '0018_character_level_up_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leakerbleed',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leakeremission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leakerprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leakervolatility',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
