# Generated by Django 5.2.12 on 2026-04-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharSheet', '0019_alter_leakerbleed_id_alter_leakeremission_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.CharField(choices=[('ION_OPERATIVE', 'ION Operative'), ('PIRATE', 'Pirate'), ('AMNESIAC', 'Amnesiac'), ('REVOLUTIONARY', 'Revolutionary Agitator'), ('EXECUTIONER', 'Executioner of the Republic'), ('GUNSLINGER', 'Frontier Gunslinger'), ('SWORDSMAN', 'Wandering Swordsman'), ('ION_RESEARCHER', 'ION Researcher'), ('MARSHAL', 'Marshal of the Republic'), ('FIELD_MEDIC', 'Field Medic'), ('STREET_OPERATOR', 'Street Operator'), ('NULL_SCAVENGER', 'Null-Born Scavenger'), ('SCHOLAR', 'Displaced Scholar'), ('EXILED_SOLDIER', 'Exiled Soldier'), ('DRIFTER', 'Drifter'), ('OTHER', 'Outro')], default='OTHER', max_length=20, verbose_name='Background'),
        ),
    ]
